# Generated by Codex on 2026-04-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_image_url_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='banner_image',
        ),
        migrations.AlterField(
            model_name='post',
            name='banner_image',
            field=models.ImageField(blank=True, upload_to='posts/banners/'),
        ),
        migrations.AddField(
            model_name='post',
            name='body_image',
            field=models.ImageField(blank=True, upload_to='posts/body/'),
        ),
    ]
