# Generated by Django 6.0.4 on 2026-04-20 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tag_post_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='posts/gallery/')),
                ('caption', models.CharField(blank=True, max_length=140)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.post')),
            ],
            options={
                'verbose_name': 'imagen de galeria',
                'verbose_name_plural': 'imagenes de galeria',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
